- src/devcenter/azext_devcenter/tests/latest/preparers.py
- src/devcenter/azext_devcenter/tests/latest/recordings/test_devcenter_Scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_network_connection_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_project_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
> Add project and network connection tests

- src/devcenter/azext_devcenter/tests/latest/helper.py
- src/devcenter/azext_devcenter/tests/latest/recordings/test_catalog_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_env_type_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_proj_env_type_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
> Add catalog and env type tests

- .github/CODEOWNERS
- src/devcenter/README.md
> Fix wording of readme

- src/devcenter/README.md
> Update extension name in read me

- src/devcenter/azext_devcenter/generated/_help.py
- src/devcenter/azext_devcenter/manual/helper.py
- src/devcenter/azext_devcenter/tests/latest/helper.py
- src/service_name.json
> Fix PR build errors

- src/devcenter/azext_devcenter/tests/latest/recordings/test_gallery_scenario.yaml
- src/devcenter/azext_devcenter/vendored_sdks/devcenter_dataplane/aio/operations/_pool_operations.py
> Fix pool operation and gallery tests

- src/devcenter/azext_devcenter/tests/latest/recordings/test_catalog_item_dataplane_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_catalog_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_dev_center_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_env_type_dataplane_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_environment_dataplane_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_gallery_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_proj_env_type_scenario.yaml
> Update managed identity api version

- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/pool/_update.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/schedule/_update.py
- src/devcenter/azext_devcenter/custom.py
> Remove unused update args

- linter_exclusions.yml
- src/devcenter/azext_devcenter/_help.py
- src/devcenter/azext_devcenter/_params.py
- src/devcenter/azext_devcenter/commands.py
- src/devcenter/azext_devcenter/custom.py
> Add update environment command

- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/catalog/_sync.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/pool/_run_health_check.py
- src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
> Update control plane tests for 2023-01-01-preview

- src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
> Update data plane tests 2023-01-01-preview

- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/attached_network/_list.py
> Fix list attached network description

- src/devcenter/azext_devcenter/_help.py
- src/devcenter/azext_devcenter/_params.py
- src/devcenter/azext_devcenter/_validators.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/network_connection/_create.py
- src/devcenter/azext_devcenter/commands.py
- src/devcenter/azext_devcenter/custom.py
- src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
> Improvements to commands

- src/devcenter/azext_devcenter/_client_factory.py
- src/devcenter/azext_devcenter/_help.py
- src/devcenter/azext_devcenter/_params.py
- src/devcenter/azext_devcenter/_validators.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/attached_network/_list.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/attached_network/_show.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_list.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_show.py
- src/devcenter/azext_devcenter/custom.py
- src/devcenter/azext_devcenter/utils.py
> Add endpoint option to data plane cmds, improve error handling

- src/devcenter/azext_devcenter/_validators.py
- src/devcenter/azext_devcenter/custom.py
> Fix endpoint regex, update to dev box list

- src/devcenter/azext_devcenter/_validators.py
> Improve endpoint error message

- src/devcenter/azext_devcenter/_validators.py
> Further improve error message string

- src/devcenter/HISTORY.rst
- src/devcenter/azext_devcenter/azext_metadata.json
> Add breaking changes to HISTORY.rst

- src/devcenter/HISTORY.rst
- src/devcenter/azext_devcenter/_help.py
- src/devcenter/azext_devcenter/_validators.py
- src/devcenter/setup.py
> Fix env create error string, update dp help

- src/devcenter/HISTORY.rst
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_create.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_delete.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_show.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_update.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/devbox_definition/_wait.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/pool/_create.py
- src/devcenter/azext_devcenter/aaz/latest/devcenter/admin/pool/_update.py
- src/devcenter/setup.py
> Update dev box definition parameter

- src/devcenter/HISTORY.rst
- src/devcenter/setup.py
> Update version to 2.0.0

- src/devcenter/azext_devcenter/tests/latest/recordings/test_attached_network_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_dev_box_dataplane_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_dev_box_repair_dataplane_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_gallery_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_network_connection_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_dataplane_scenario.yaml
- src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_scenario.yaml
> revert network fix

- src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_dataplane_scenario.yaml
> Fix pool test

- src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_dataplane_scenario.yaml
> Fix pool tests

- src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_dataplane_scenario.yaml
> Fix subnet
